server:
  port: 8080

spring:
  application:
    name: service-user
  #  devtools:
  #  restart:
  #    poll-interval: 3000ms
  #    quiet-period: 2999ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mysql
    password: mysql
    url: jdbc:mysql://47.94.4.93:3306/db_mirror?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&allowPublicKeyRetrieval=true

#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.xml

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    cn:
      dbdj1201:
        egg:
          chick:
            mapper : debug